# Generated by Django 5.0.6 on 2024-07-08 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cliente', models.CharField(max_length=6, unique=True)),
                ('created_by', models.EmailField(max_length=254)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('fecha_fiesta', models.DateField()),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('prefijo', models.CharField(max_length=3)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('ubicacion', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=50)),
                ('como_nos_conocio', models.CharField(max_length=50)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('vendedora', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_producto', models.CharField(max_length=6, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('talla', models.CharField(max_length=10)),
                ('pvp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imagen', models.URLField(blank=True, null=True)),
                ('estado', models.CharField(max_length=50)),
                ('tienda', models.CharField(max_length=50)),
                ('cantidad_madrid', models.IntegerField(default=0)),
                ('cantidad_barcelona', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_venta', models.CharField(max_length=6, unique=True)),
                ('created_by', models.EmailField(max_length=254)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('tienda', models.CharField(max_length=50)),
                ('envio_entrega', models.BooleanField(default=False)),
                ('estado_entrega', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=50)),
                ('fecha_entrega', models.DateField()),
                ('fecha_devolucion', models.DateField(blank=True, null=True)),
                ('total_pagar', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_pagado', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pendiente_pago', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_pago', models.CharField(max_length=6, unique=True)),
                ('created_by', models.EmailField(max_length=254)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('tienda', models.CharField(max_length=50)),
                ('metodo_pago', models.CharField(max_length=50)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=10)),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.venta')),
            ],
        ),
        migrations.CreateModel(
            name='VentaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.producto')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.venta')),
            ],
        ),
    ]
