# Generated by Django 5.0.6 on 2024-07-08 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='cantidad_valencia',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='producto',
            name='cantidad_videollamada',
            field=models.IntegerField(default=0),
        ),
    ]
