# Generated by Django 5.0.6 on 2024-07-08 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_producto_cantidad_valencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='estado_cliente',
            field=models.CharField(choices=[('ya compró', 'Ya Compró'), ('perdido', 'Perdido'), ('Con Cita', 'Con Cita')], default='Con Cita', max_length=50),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='como_nos_conocio',
            field=models.CharField(choices=[('Google', 'Google'), ('Google maps', 'Google Maps'), ('Instagram', 'Instagram'), ('Facebook', 'Facebook'), ('Recomendación', 'Recomendación'), ('Milanuncios', 'Milanuncios'), ('Web', 'Web'), ('Otro', 'Otro')], max_length=50),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='estado',
            field=models.CharField(choices=[('sin cita', 'Sin Cita'), ('con cita', 'Con Cita'), ('perdido', 'Perdido'), ('eliminar cliente duplicado', 'Eliminar Cliente Duplicado')], max_length=50),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='id_cliente',
            field=models.CharField(default='UNIQUEID', max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='prefijo',
            field=models.CharField(choices=[('+34', '+34'), ('+1', '+1'), ('+44', '+44')], max_length=3),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='ubicacion',
            field=models.CharField(choices=[('Madrid', 'Madrid'), ('Barcelona', 'Barcelona'), ('Valencia', 'Valencia'), ('Videollamada', 'Videollamada')], max_length=50),
        ),
        migrations.AlterField(
            model_name='pago',
            name='id_pago',
            field=models.CharField(default='UNIQUEID', max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='pago',
            name='metodo_pago',
            field=models.CharField(choices=[('Efectivo', 'Efectivo'), ('Tarjeta', 'Tarjeta'), ('BBVA', 'BBVA'), ('SumUp', 'SumUp'), ('Bizum', 'Bizum'), ('Transferencia', 'Transferencia'), ('Paypal', 'Paypal'), ('Web', 'Web')], max_length=50),
        ),
        migrations.AlterField(
            model_name='pago',
            name='tienda',
            field=models.CharField(choices=[('Madrid', 'Madrid'), ('Barcelona', 'Barcelona'), ('Valencia', 'Valencia'), ('Videollamada', 'Videollamada')], max_length=50),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('Vestido', 'Vestido'), ('Vestido Corto', 'Vestido Corto'), ('Accesorios', 'Accesorios'), ('Complementos', 'Complementos'), ('Envio', 'Envio'), ('Invitaciones', 'Invitaciones'), ('Paquete Fotos', 'Paquete Fotos'), ('Recuerdos', 'Recuerdos'), ('Otros', 'Otros')], max_length=50),
        ),
        migrations.AlterField(
            model_name='producto',
            name='estado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Baja', 'Baja')], max_length=50),
        ),
        migrations.AlterField(
            model_name='producto',
            name='id_producto',
            field=models.CharField(default='UNIQUEID', max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tienda',
            field=models.CharField(choices=[('Madrid', 'Madrid'), ('Barcelona', 'Barcelona'), ('Valencia', 'Valencia'), ('Videollamada', 'Videollamada')], max_length=50),
        ),
        migrations.AlterField(
            model_name='venta',
            name='estado_entrega',
            field=models.CharField(choices=[('Por Entregar o Enviar', 'Por Entregar o Enviar'), ('Entregado o Enviado', 'Entregado o Enviado'), ('Vestido Devuelto', 'Vestido Devuelto')], max_length=50),
        ),
        migrations.AlterField(
            model_name='venta',
            name='id_venta',
            field=models.CharField(default='UNIQUEID', max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='tienda',
            field=models.CharField(choices=[('Madrid', 'Madrid'), ('Barcelona', 'Barcelona'), ('Valencia', 'Valencia'), ('Videollamada', 'Videollamada')], max_length=50),
        ),
        migrations.AlterField(
            model_name='venta',
            name='tipo',
            field=models.CharField(choices=[('Alquiler', 'Alquiler'), ('Venta', 'Venta')], max_length=50),
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_pedido', models.DateTimeField(auto_now_add=True)),
                ('estado_pedido', models.CharField(max_length=50)),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.venta')),
            ],
        ),
        migrations.CreateModel(
            name='SesionFoto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_sesion', models.DateTimeField(auto_now_add=True)),
                ('estado_sesion', models.CharField(max_length=50)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='LogSesion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('accion', models.CharField(max_length=50)),
                ('sesion_foto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sesionfoto')),
            ],
        ),
    ]
