# Generated by Django 5.0.6 on 2024-07-08 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_cliente_estado_cliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='id_cliente',
            field=models.CharField(default='UNIQUEID', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='pago',
            name='id_pago',
            field=models.CharField(default='UNIQUEID', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='id_producto',
            field=models.CharField(default='UNIQUEID', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='id_venta',
            field=models.CharField(default='UNIQUEID', max_length=20, unique=True),
        ),
    ]
