# Generated by Django 5.0.6 on 2024-07-09 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_historicalproductoalquiler_historicalproductoventa_and_more'),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='id_productos',
        ),
        migrations.AddField(
            model_name='venta',
            name='productos_alquiler',
            field=models.ManyToManyField(blank=True, to='productos.productoalquiler'),
        ),
        migrations.AddField(
            model_name='venta',
            name='productos_venta',
            field=models.ManyToManyField(blank=True, to='productos.productoventa'),
        ),
        migrations.AlterField(
            model_name='historicalventa',
            name='id_ventas',
            field=models.CharField(db_index=True, max_length=6),
        ),
        migrations.AlterField(
            model_name='venta',
            name='id_ventas',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
