# Generated by Django 5.0.6 on 2024-07-10 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_remove_venta_id_productos_venta_productos_alquiler_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalventa',
            name='id_ventas',
            field=models.CharField(db_index=True, default='B6A042', max_length=6),
        ),
        migrations.AlterField(
            model_name='venta',
            name='id_ventas',
            field=models.CharField(default='B6A042', max_length=6, unique=True),
        ),
    ]
