# Generated by Django 5.0.6 on 2024-07-10 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_alter_historicalventa_id_ventas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalventa',
            name='id_ventas',
            field=models.CharField(db_index=True, default='C2D828', max_length=6),
        ),
        migrations.AlterField(
            model_name='venta',
            name='id_ventas',
            field=models.CharField(default='C2D828', max_length=6, unique=True),
        ),
    ]
