# Generated by Django 5.0.6 on 2024-07-10 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_alter_historicalpedido_estado_alter_pedido_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpedido',
            name='id_pedido',
            field=models.CharField(db_index=True, default='4A4F29', max_length=6),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='id_pedido',
            field=models.CharField(default='4A4F29', max_length=6, unique=True),
        ),
    ]
