# Generated by Django 5.0.6 on 2024-07-09 21:33

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_productos', models.CharField(max_length=6, unique=True)),
                ('label_precio', models.CharField(max_length=255)),
                ('almacen_m', models.IntegerField(default=0)),
                ('madrid', models.IntegerField(default=0)),
                ('barcelona', models.IntegerField(default=0)),
                ('tienda', models.CharField(choices=[('Madrid', 'Madrid'), ('Barcelona', 'Barcelona'), ('Valencia', 'Valencia'), ('Videollamada', 'Videollamada')], max_length=20)),
                ('categoria', models.CharField(choices=[('Vestido', 'Vestido'), ('Vestido Corto', 'Vestido Corto'), ('Accesorios', 'Accesorios'), ('Complementos', 'Complementos'), ('Envio', 'Envio'), ('Invitaciones', 'Invitaciones'), ('Paquete Fotos', 'Paquete Fotos'), ('Recuerdos', 'Recuerdos'), ('Otros', 'Otros')], max_length=50)),
                ('nombre', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=50)),
                ('talla', models.CharField(max_length=50)),
                ('pvp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Baja', 'Baja')], max_length=50)),
                ('nombres', models.CharField(max_length=255)),
                ('reservados', models.IntegerField(default=0)),
                ('disponibles', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalProducto',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('id_productos', models.CharField(db_index=True, max_length=6)),
                ('label_precio', models.CharField(max_length=255)),
                ('almacen_m', models.IntegerField(default=0)),
                ('madrid', models.IntegerField(default=0)),
                ('barcelona', models.IntegerField(default=0)),
                ('tienda', models.CharField(choices=[('Madrid', 'Madrid'), ('Barcelona', 'Barcelona'), ('Valencia', 'Valencia'), ('Videollamada', 'Videollamada')], max_length=20)),
                ('categoria', models.CharField(choices=[('Vestido', 'Vestido'), ('Vestido Corto', 'Vestido Corto'), ('Accesorios', 'Accesorios'), ('Complementos', 'Complementos'), ('Envio', 'Envio'), ('Invitaciones', 'Invitaciones'), ('Paquete Fotos', 'Paquete Fotos'), ('Recuerdos', 'Recuerdos'), ('Otros', 'Otros')], max_length=50)),
                ('nombre', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=50)),
                ('talla', models.CharField(max_length=50)),
                ('pvp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.TextField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Baja', 'Baja')], max_length=50)),
                ('nombres', models.CharField(max_length=255)),
                ('reservados', models.IntegerField(default=0)),
                ('disponibles', models.IntegerField(default=0)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical producto',
                'verbose_name_plural': 'historical productos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
