# Generated by Django 5.0.6 on 2024-07-09 22:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_historicalproductoalquiler_historicalproductoventa_and_more'),
        ('ventas', '0002_remove_venta_id_productos_venta_productos_alquiler_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='Producto',
        ),
        migrations.AddField(
            model_name='historicalproductoalquiler',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalproductoventa',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reservaalquiler',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.productoalquiler'),
        ),
        migrations.DeleteModel(
            name='HistoricalProducto',
        ),
    ]
