# Generated by Django 5.0.6 on 2024-07-10 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_delete_producto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproductoalquiler',
            name='id_producto',
            field=models.CharField(db_index=True, default='A37B7E', max_length=6),
        ),
        migrations.AlterField(
            model_name='historicalproductoventa',
            name='id_producto',
            field=models.CharField(db_index=True, default='EB8DA5', max_length=6),
        ),
        migrations.AlterField(
            model_name='productoalquiler',
            name='id_producto',
            field=models.CharField(default='A37B7E', max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='productoventa',
            name='id_producto',
            field=models.CharField(default='EB8DA5', max_length=6, unique=True),
        ),
    ]
