# Generated by Django 5.0.6 on 2024-07-10 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_alter_historicalproductoalquiler_id_producto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproductoalquiler',
            name='id_producto',
            field=models.CharField(db_index=True, default='436741', max_length=6),
        ),
        migrations.AlterField(
            model_name='historicalproductoventa',
            name='id_producto',
            field=models.CharField(db_index=True, default='9FF7EA', max_length=6),
        ),
        migrations.AlterField(
            model_name='productoalquiler',
            name='id_producto',
            field=models.CharField(default='436741', max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='productoventa',
            name='id_producto',
            field=models.CharField(default='9FF7EA', max_length=6, unique=True),
        ),
    ]
