# Generated by Django 5.0.6 on 2024-07-10 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_cliente_fecha_fiesta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='duplicados',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='whatsapp',
        ),
        migrations.RemoveField(
            model_name='historicalcliente',
            name='duplicados',
        ),
        migrations.RemoveField(
            model_name='historicalcliente',
            name='whatsapp',
        ),
    ]
