# Generated by Django 5.0.6 on 2024-07-10 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_remove_cliente_duplicados_remove_cliente_whatsapp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='id_clientes',
            field=models.CharField(default='573817', max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='historicalcliente',
            name='id_clientes',
            field=models.CharField(db_index=True, default='573817', max_length=6),
        ),
    ]
