# Generated by Django 5.0.6 on 2024-07-09 21:33

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ventas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalSesionFoto',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('id_sesion', models.CharField(db_index=True, max_length=6)),
                ('fecha_sesion', models.DateTimeField()),
                ('lugar_sesion', models.CharField(max_length=255)),
                ('nombre_fotografo', models.CharField(max_length=255)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('fotos_entregadas', models.BooleanField(default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('id_ventas', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ventas.venta')),
            ],
            options={
                'verbose_name': 'historical sesion foto',
                'verbose_name_plural': 'historical sesion fotos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='SesionFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_sesion', models.CharField(max_length=6, unique=True)),
                ('fecha_sesion', models.DateTimeField()),
                ('lugar_sesion', models.CharField(max_length=255)),
                ('nombre_fotografo', models.CharField(max_length=255)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('fotos_entregadas', models.BooleanField(default=False)),
                ('id_ventas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones_fotos', to='ventas.venta')),
            ],
        ),
    ]
