# Generated by Django 5.0.6 on 2024-07-10 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sesiones_fotos', '0002_remove_sesionfoto_id_ventas_historicalsesionfotos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsesionfotos',
            name='id_sesion',
            field=models.CharField(db_index=True, default='63228C', max_length=6),
        ),
        migrations.AlterField(
            model_name='sesionfotos',
            name='id_sesion',
            field=models.CharField(default='63228C', max_length=6, unique=True),
        ),
    ]
