# Generated by Django 5.0.6 on 2024-07-10 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sesiones_fotos', '0003_alter_historicalsesionfotos_id_sesion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsesionfotos',
            name='id_sesion',
            field=models.CharField(db_index=True, default='A9D86B', max_length=6),
        ),
        migrations.AlterField(
            model_name='sesionfotos',
            name='id_sesion',
            field=models.CharField(default='A9D86B', max_length=6, unique=True),
        ),
    ]
